apiVersion: customhostname.upbound.io/v1alpha1
kind: FallbackOrigin
metadata:
  annotations:
    meta.upbound.io/example-id: customhostname/v1alpha1/fallbackorigin
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    origin: fallback.example.com
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
