apiVersion: warp.upbound.io/v1alpha1
kind: SplitTunnel
metadata:
  annotations:
    meta.upbound.io/example-id: warp/v1alpha1/splittunnel
  labels:
    testing.upbound.io/example-name: example_split_tunnel_exclude
  name: example-split-tunnel-exclude
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    mode: exclude
    tunnels:
    - description: example domain
      host: '*.example.com'

---

apiVersion: warp.upbound.io/v1alpha1
kind: DeviceSettingsPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: warp/v1alpha1/splittunnel
  labels:
    testing.upbound.io/example-name: developer_warp_policy
  name: developer-warp-policy
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    match: any(identity.groups.name[*] in {"Developers"})
    name: Developers
    precedence: 10
    switchLocked: true
