// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type InitialSettingsInitParameters struct {
}

type InitialSettingsObservation struct {

	// (String)
	AlwaysOnline *string `json:"alwaysOnline,omitempty" tf:"always_online,omitempty"`

	// (String)
	AlwaysUseHTTPS *string `json:"alwaysUseHttps,omitempty" tf:"always_use_https,omitempty"`

	// (String)
	AutomaticHTTPSRewrites *string `json:"automaticHttpsRewrites,omitempty" tf:"automatic_https_rewrites,omitempty"`

	// (String)
	BinaryAst *string `json:"binaryAst,omitempty" tf:"binary_ast,omitempty"`

	// (String)
	Brotli *string `json:"brotli,omitempty" tf:"brotli,omitempty"`

	// (Number)
	BrowserCacheTTL *float64 `json:"browserCacheTtl,omitempty" tf:"browser_cache_ttl,omitempty"`

	// (String)
	BrowserCheck *string `json:"browserCheck,omitempty" tf:"browser_check,omitempty"`

	// (String)
	CacheLevel *string `json:"cacheLevel,omitempty" tf:"cache_level,omitempty"`

	// (Number)
	ChallengeTTL *float64 `json:"challengeTtl,omitempty" tf:"challenge_ttl,omitempty"`

	// (List of String)
	Ciphers []*string `json:"ciphers,omitempty" tf:"ciphers,omitempty"`

	// (String)
	CnameFlattening *string `json:"cnameFlattening,omitempty" tf:"cname_flattening,omitempty"`

	// (String)
	DevelopmentMode *string `json:"developmentMode,omitempty" tf:"development_mode,omitempty"`

	// (String)
	EarlyHints *string `json:"earlyHints,omitempty" tf:"early_hints,omitempty"`

	// (String)
	EmailObfuscation *string `json:"emailObfuscation,omitempty" tf:"email_obfuscation,omitempty"`

	// (String)
	FilterLogsToCloudflare *string `json:"filterLogsToCloudflare,omitempty" tf:"filter_logs_to_cloudflare,omitempty"`

	// (String)
	Fonts *string `json:"fonts,omitempty" tf:"fonts,omitempty"`

	// (String)
	H2Prioritization *string `json:"h2Prioritization,omitempty" tf:"h2_prioritization,omitempty"`

	// (String)
	HotlinkProtection *string `json:"hotlinkProtection,omitempty" tf:"hotlink_protection,omitempty"`

	// (String)
	Http2 *string `json:"http2,omitempty" tf:"http2,omitempty"`

	// (String)
	Http3 *string `json:"http3,omitempty" tf:"http3,omitempty"`

	// (String)
	IPGeolocation *string `json:"ipGeolocation,omitempty" tf:"ip_geolocation,omitempty"`

	// (String)
	IPv6 *string `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// (String)
	ImageResizing *string `json:"imageResizing,omitempty" tf:"image_resizing,omitempty"`

	// (String)
	LogToCloudflare *string `json:"logToCloudflare,omitempty" tf:"log_to_cloudflare,omitempty"`

	// (Number)
	MaxUpload *float64 `json:"maxUpload,omitempty" tf:"max_upload,omitempty"`

	// (String)
	MinTLSVersion *string `json:"minTlsVersion,omitempty" tf:"min_tls_version,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	Minify []MinifyObservation `json:"minify,omitempty" tf:"minify,omitempty"`

	// (String)
	Mirage *string `json:"mirage,omitempty" tf:"mirage,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	MobileRedirect []MobileRedirectObservation `json:"mobileRedirect,omitempty" tf:"mobile_redirect,omitempty"`

	// (String)
	OpportunisticEncryption *string `json:"opportunisticEncryption,omitempty" tf:"opportunistic_encryption,omitempty"`

	// (String)
	OpportunisticOnion *string `json:"opportunisticOnion,omitempty" tf:"opportunistic_onion,omitempty"`

	// (String)
	OrangeToOrange *string `json:"orangeToOrange,omitempty" tf:"orange_to_orange,omitempty"`

	// (String)
	OriginErrorPagePassThru *string `json:"originErrorPagePassThru,omitempty" tf:"origin_error_page_pass_thru,omitempty"`

	// (String)
	OriginMaxHTTPVersion *string `json:"originMaxHttpVersion,omitempty" tf:"origin_max_http_version,omitempty"`

	// (String)
	Polish *string `json:"polish,omitempty" tf:"polish,omitempty"`

	// (String)
	PrefetchPreload *string `json:"prefetchPreload,omitempty" tf:"prefetch_preload,omitempty"`

	// (String)
	PrivacyPass *string `json:"privacyPass,omitempty" tf:"privacy_pass,omitempty"`

	// (String)
	ProxyReadTimeout *string `json:"proxyReadTimeout,omitempty" tf:"proxy_read_timeout,omitempty"`

	// (String)
	PseudoIPv4 *string `json:"pseudoIpv4,omitempty" tf:"pseudo_ipv4,omitempty"`

	// (String)
	ResponseBuffering *string `json:"responseBuffering,omitempty" tf:"response_buffering,omitempty"`

	// (String)
	RocketLoader *string `json:"rocketLoader,omitempty" tf:"rocket_loader,omitempty"`

	// (String)
	SSL *string `json:"ssl,omitempty" tf:"ssl,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	SecurityHeader []SecurityHeaderObservation `json:"securityHeader,omitempty" tf:"security_header,omitempty"`

	// (String)
	SecurityLevel *string `json:"securityLevel,omitempty" tf:"security_level,omitempty"`

	// (String)
	ServerSideExclude *string `json:"serverSideExclude,omitempty" tf:"server_side_exclude,omitempty"`

	// (String)
	SortQueryStringForCache *string `json:"sortQueryStringForCache,omitempty" tf:"sort_query_string_for_cache,omitempty"`

	// (String, Deprecated)
	TLS12Only *string `json:"tls12Only,omitempty" tf:"tls_1_2_only,omitempty"`

	// (String)
	TLS13 *string `json:"tls13,omitempty" tf:"tls_1_3,omitempty"`

	// (String)
	TLSClientAuth *string `json:"tlsClientAuth,omitempty" tf:"tls_client_auth,omitempty"`

	// (String)
	TrueClientIPHeader *string `json:"trueClientIpHeader,omitempty" tf:"true_client_ip_header,omitempty"`

	// (String)
	UniversalSSL *string `json:"universalSsl,omitempty" tf:"universal_ssl,omitempty"`

	// (String)
	VisitorIP *string `json:"visitorIp,omitempty" tf:"visitor_ip,omitempty"`

	// (String)
	Waf *string `json:"waf,omitempty" tf:"waf,omitempty"`

	// (String)
	Webp *string `json:"webp,omitempty" tf:"webp,omitempty"`

	// (String)
	Websockets *string `json:"websockets,omitempty" tf:"websockets,omitempty"`

	// (String)
	ZeroRtt *string `json:"zeroRtt,omitempty" tf:"zero_rtt,omitempty"`
}

type InitialSettingsParameters struct {
}

type MinifyInitParameters struct {
}

type MinifyObservation struct {

	// (String)
	CSS *string `json:"css,omitempty" tf:"css,omitempty"`

	// (String)
	HTML *string `json:"html,omitempty" tf:"html,omitempty"`

	// (String)
	Js *string `json:"js,omitempty" tf:"js,omitempty"`
}

type MinifyParameters struct {
}

type MobileRedirectInitParameters struct {
}

type MobileRedirectObservation struct {

	// (String)
	MobileSubdomain *string `json:"mobileSubdomain,omitempty" tf:"mobile_subdomain,omitempty"`

	// (String)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (Boolean)
	StripURI *bool `json:"stripUri,omitempty" tf:"strip_uri,omitempty"`
}

type MobileRedirectParameters struct {
}

type SecurityHeaderInitParameters struct {
}

type SecurityHeaderObservation struct {

	// (Boolean)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean)
	IncludeSubdomains *bool `json:"includeSubdomains,omitempty" tf:"include_subdomains,omitempty"`

	// (Number)
	MaxAge *float64 `json:"maxAge,omitempty" tf:"max_age,omitempty"`

	// (Boolean)
	Nosniff *bool `json:"nosniff,omitempty" tf:"nosniff,omitempty"`

	// (Boolean)
	Preload *bool `json:"preload,omitempty" tf:"preload,omitempty"`
}

type SecurityHeaderParameters struct {
}

type SettingsInitParameters struct {

	// (String)
	AlwaysOnline *string `json:"alwaysOnline,omitempty" tf:"always_online,omitempty"`

	// (String)
	AlwaysUseHTTPS *string `json:"alwaysUseHttps,omitempty" tf:"always_use_https,omitempty"`

	// (String)
	AutomaticHTTPSRewrites *string `json:"automaticHttpsRewrites,omitempty" tf:"automatic_https_rewrites,omitempty"`

	// (String)
	BinaryAst *string `json:"binaryAst,omitempty" tf:"binary_ast,omitempty"`

	// (String)
	Brotli *string `json:"brotli,omitempty" tf:"brotli,omitempty"`

	// (Number)
	BrowserCacheTTL *float64 `json:"browserCacheTtl,omitempty" tf:"browser_cache_ttl,omitempty"`

	// (String)
	BrowserCheck *string `json:"browserCheck,omitempty" tf:"browser_check,omitempty"`

	// (String)
	CacheLevel *string `json:"cacheLevel,omitempty" tf:"cache_level,omitempty"`

	// (Number)
	ChallengeTTL *float64 `json:"challengeTtl,omitempty" tf:"challenge_ttl,omitempty"`

	// (List of String)
	Ciphers []*string `json:"ciphers,omitempty" tf:"ciphers,omitempty"`

	// (String)
	CnameFlattening *string `json:"cnameFlattening,omitempty" tf:"cname_flattening,omitempty"`

	// (String)
	DevelopmentMode *string `json:"developmentMode,omitempty" tf:"development_mode,omitempty"`

	// (String)
	EarlyHints *string `json:"earlyHints,omitempty" tf:"early_hints,omitempty"`

	// (String)
	EmailObfuscation *string `json:"emailObfuscation,omitempty" tf:"email_obfuscation,omitempty"`

	// (String)
	FilterLogsToCloudflare *string `json:"filterLogsToCloudflare,omitempty" tf:"filter_logs_to_cloudflare,omitempty"`

	// (String)
	Fonts *string `json:"fonts,omitempty" tf:"fonts,omitempty"`

	// (String)
	H2Prioritization *string `json:"h2Prioritization,omitempty" tf:"h2_prioritization,omitempty"`

	// (String)
	HotlinkProtection *string `json:"hotlinkProtection,omitempty" tf:"hotlink_protection,omitempty"`

	// (String)
	Http2 *string `json:"http2,omitempty" tf:"http2,omitempty"`

	// (String)
	Http3 *string `json:"http3,omitempty" tf:"http3,omitempty"`

	// (String)
	IPGeolocation *string `json:"ipGeolocation,omitempty" tf:"ip_geolocation,omitempty"`

	// (String)
	IPv6 *string `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// (String)
	ImageResizing *string `json:"imageResizing,omitempty" tf:"image_resizing,omitempty"`

	// (String)
	LogToCloudflare *string `json:"logToCloudflare,omitempty" tf:"log_to_cloudflare,omitempty"`

	// (Number)
	MaxUpload *float64 `json:"maxUpload,omitempty" tf:"max_upload,omitempty"`

	// (String)
	MinTLSVersion *string `json:"minTlsVersion,omitempty" tf:"min_tls_version,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	Minify []SettingsMinifyInitParameters `json:"minify,omitempty" tf:"minify,omitempty"`

	// (String)
	Mirage *string `json:"mirage,omitempty" tf:"mirage,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	MobileRedirect []SettingsMobileRedirectInitParameters `json:"mobileRedirect,omitempty" tf:"mobile_redirect,omitempty"`

	// (String)
	OpportunisticEncryption *string `json:"opportunisticEncryption,omitempty" tf:"opportunistic_encryption,omitempty"`

	// (String)
	OpportunisticOnion *string `json:"opportunisticOnion,omitempty" tf:"opportunistic_onion,omitempty"`

	// (String)
	OrangeToOrange *string `json:"orangeToOrange,omitempty" tf:"orange_to_orange,omitempty"`

	// (String)
	OriginErrorPagePassThru *string `json:"originErrorPagePassThru,omitempty" tf:"origin_error_page_pass_thru,omitempty"`

	// (String)
	OriginMaxHTTPVersion *string `json:"originMaxHttpVersion,omitempty" tf:"origin_max_http_version,omitempty"`

	// (String)
	Polish *string `json:"polish,omitempty" tf:"polish,omitempty"`

	// (String)
	PrefetchPreload *string `json:"prefetchPreload,omitempty" tf:"prefetch_preload,omitempty"`

	// (String)
	PrivacyPass *string `json:"privacyPass,omitempty" tf:"privacy_pass,omitempty"`

	// (String)
	ProxyReadTimeout *string `json:"proxyReadTimeout,omitempty" tf:"proxy_read_timeout,omitempty"`

	// (String)
	PseudoIPv4 *string `json:"pseudoIpv4,omitempty" tf:"pseudo_ipv4,omitempty"`

	// (String)
	ResponseBuffering *string `json:"responseBuffering,omitempty" tf:"response_buffering,omitempty"`

	// (String)
	RocketLoader *string `json:"rocketLoader,omitempty" tf:"rocket_loader,omitempty"`

	// (String)
	SSL *string `json:"ssl,omitempty" tf:"ssl,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	SecurityHeader []SettingsSecurityHeaderInitParameters `json:"securityHeader,omitempty" tf:"security_header,omitempty"`

	// (String)
	SecurityLevel *string `json:"securityLevel,omitempty" tf:"security_level,omitempty"`

	// (String)
	ServerSideExclude *string `json:"serverSideExclude,omitempty" tf:"server_side_exclude,omitempty"`

	// (String)
	SortQueryStringForCache *string `json:"sortQueryStringForCache,omitempty" tf:"sort_query_string_for_cache,omitempty"`

	// (String, Deprecated)
	TLS12Only *string `json:"tls12Only,omitempty" tf:"tls_1_2_only,omitempty"`

	// (String)
	TLS13 *string `json:"tls13,omitempty" tf:"tls_1_3,omitempty"`

	// (String)
	TLSClientAuth *string `json:"tlsClientAuth,omitempty" tf:"tls_client_auth,omitempty"`

	// (String)
	TrueClientIPHeader *string `json:"trueClientIpHeader,omitempty" tf:"true_client_ip_header,omitempty"`

	// (String)
	UniversalSSL *string `json:"universalSsl,omitempty" tf:"universal_ssl,omitempty"`

	// (String)
	VisitorIP *string `json:"visitorIp,omitempty" tf:"visitor_ip,omitempty"`

	// (String)
	Waf *string `json:"waf,omitempty" tf:"waf,omitempty"`

	// (String)
	Webp *string `json:"webp,omitempty" tf:"webp,omitempty"`

	// (String)
	Websockets *string `json:"websockets,omitempty" tf:"websockets,omitempty"`

	// (String)
	ZeroRtt *string `json:"zeroRtt,omitempty" tf:"zero_rtt,omitempty"`
}

type SettingsMinifyInitParameters struct {

	// (String)
	CSS *string `json:"css,omitempty" tf:"css,omitempty"`

	// (String)
	HTML *string `json:"html,omitempty" tf:"html,omitempty"`

	// (String)
	Js *string `json:"js,omitempty" tf:"js,omitempty"`
}

type SettingsMinifyObservation struct {

	// (String)
	CSS *string `json:"css,omitempty" tf:"css,omitempty"`

	// (String)
	HTML *string `json:"html,omitempty" tf:"html,omitempty"`

	// (String)
	Js *string `json:"js,omitempty" tf:"js,omitempty"`
}

type SettingsMinifyParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	CSS *string `json:"css" tf:"css,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	HTML *string `json:"html" tf:"html,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Js *string `json:"js" tf:"js,omitempty"`
}

type SettingsMobileRedirectInitParameters struct {

	// (String)
	MobileSubdomain *string `json:"mobileSubdomain,omitempty" tf:"mobile_subdomain,omitempty"`

	// (String)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (Boolean)
	StripURI *bool `json:"stripUri,omitempty" tf:"strip_uri,omitempty"`
}

type SettingsMobileRedirectObservation struct {

	// (String)
	MobileSubdomain *string `json:"mobileSubdomain,omitempty" tf:"mobile_subdomain,omitempty"`

	// (String)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (Boolean)
	StripURI *bool `json:"stripUri,omitempty" tf:"strip_uri,omitempty"`
}

type SettingsMobileRedirectParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	MobileSubdomain *string `json:"mobileSubdomain" tf:"mobile_subdomain,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Status *string `json:"status" tf:"status,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	StripURI *bool `json:"stripUri" tf:"strip_uri,omitempty"`
}

type SettingsObservation struct {

	// (String)
	AlwaysOnline *string `json:"alwaysOnline,omitempty" tf:"always_online,omitempty"`

	// (String)
	AlwaysUseHTTPS *string `json:"alwaysUseHttps,omitempty" tf:"always_use_https,omitempty"`

	// (String)
	AutomaticHTTPSRewrites *string `json:"automaticHttpsRewrites,omitempty" tf:"automatic_https_rewrites,omitempty"`

	// (String)
	BinaryAst *string `json:"binaryAst,omitempty" tf:"binary_ast,omitempty"`

	// (String)
	Brotli *string `json:"brotli,omitempty" tf:"brotli,omitempty"`

	// (Number)
	BrowserCacheTTL *float64 `json:"browserCacheTtl,omitempty" tf:"browser_cache_ttl,omitempty"`

	// (String)
	BrowserCheck *string `json:"browserCheck,omitempty" tf:"browser_check,omitempty"`

	// (String)
	CacheLevel *string `json:"cacheLevel,omitempty" tf:"cache_level,omitempty"`

	// (Number)
	ChallengeTTL *float64 `json:"challengeTtl,omitempty" tf:"challenge_ttl,omitempty"`

	// (List of String)
	Ciphers []*string `json:"ciphers,omitempty" tf:"ciphers,omitempty"`

	// (String)
	CnameFlattening *string `json:"cnameFlattening,omitempty" tf:"cname_flattening,omitempty"`

	// (String)
	DevelopmentMode *string `json:"developmentMode,omitempty" tf:"development_mode,omitempty"`

	// (String)
	EarlyHints *string `json:"earlyHints,omitempty" tf:"early_hints,omitempty"`

	// (String)
	EmailObfuscation *string `json:"emailObfuscation,omitempty" tf:"email_obfuscation,omitempty"`

	// (String)
	FilterLogsToCloudflare *string `json:"filterLogsToCloudflare,omitempty" tf:"filter_logs_to_cloudflare,omitempty"`

	// (String)
	Fonts *string `json:"fonts,omitempty" tf:"fonts,omitempty"`

	// (String)
	H2Prioritization *string `json:"h2Prioritization,omitempty" tf:"h2_prioritization,omitempty"`

	// (String)
	HotlinkProtection *string `json:"hotlinkProtection,omitempty" tf:"hotlink_protection,omitempty"`

	// (String)
	Http2 *string `json:"http2,omitempty" tf:"http2,omitempty"`

	// (String)
	Http3 *string `json:"http3,omitempty" tf:"http3,omitempty"`

	// (String)
	IPGeolocation *string `json:"ipGeolocation,omitempty" tf:"ip_geolocation,omitempty"`

	// (String)
	IPv6 *string `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// (String)
	ImageResizing *string `json:"imageResizing,omitempty" tf:"image_resizing,omitempty"`

	// (String)
	LogToCloudflare *string `json:"logToCloudflare,omitempty" tf:"log_to_cloudflare,omitempty"`

	// (Number)
	MaxUpload *float64 `json:"maxUpload,omitempty" tf:"max_upload,omitempty"`

	// (String)
	MinTLSVersion *string `json:"minTlsVersion,omitempty" tf:"min_tls_version,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	Minify []SettingsMinifyObservation `json:"minify,omitempty" tf:"minify,omitempty"`

	// (String)
	Mirage *string `json:"mirage,omitempty" tf:"mirage,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	MobileRedirect []SettingsMobileRedirectObservation `json:"mobileRedirect,omitempty" tf:"mobile_redirect,omitempty"`

	// (String)
	OpportunisticEncryption *string `json:"opportunisticEncryption,omitempty" tf:"opportunistic_encryption,omitempty"`

	// (String)
	OpportunisticOnion *string `json:"opportunisticOnion,omitempty" tf:"opportunistic_onion,omitempty"`

	// (String)
	OrangeToOrange *string `json:"orangeToOrange,omitempty" tf:"orange_to_orange,omitempty"`

	// (String)
	OriginErrorPagePassThru *string `json:"originErrorPagePassThru,omitempty" tf:"origin_error_page_pass_thru,omitempty"`

	// (String)
	OriginMaxHTTPVersion *string `json:"originMaxHttpVersion,omitempty" tf:"origin_max_http_version,omitempty"`

	// (String)
	Polish *string `json:"polish,omitempty" tf:"polish,omitempty"`

	// (String)
	PrefetchPreload *string `json:"prefetchPreload,omitempty" tf:"prefetch_preload,omitempty"`

	// (String)
	PrivacyPass *string `json:"privacyPass,omitempty" tf:"privacy_pass,omitempty"`

	// (String)
	ProxyReadTimeout *string `json:"proxyReadTimeout,omitempty" tf:"proxy_read_timeout,omitempty"`

	// (String)
	PseudoIPv4 *string `json:"pseudoIpv4,omitempty" tf:"pseudo_ipv4,omitempty"`

	// (String)
	ResponseBuffering *string `json:"responseBuffering,omitempty" tf:"response_buffering,omitempty"`

	// (String)
	RocketLoader *string `json:"rocketLoader,omitempty" tf:"rocket_loader,omitempty"`

	// (String)
	SSL *string `json:"ssl,omitempty" tf:"ssl,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	SecurityHeader []SettingsSecurityHeaderObservation `json:"securityHeader,omitempty" tf:"security_header,omitempty"`

	// (String)
	SecurityLevel *string `json:"securityLevel,omitempty" tf:"security_level,omitempty"`

	// (String)
	ServerSideExclude *string `json:"serverSideExclude,omitempty" tf:"server_side_exclude,omitempty"`

	// (String)
	SortQueryStringForCache *string `json:"sortQueryStringForCache,omitempty" tf:"sort_query_string_for_cache,omitempty"`

	// (String, Deprecated)
	TLS12Only *string `json:"tls12Only,omitempty" tf:"tls_1_2_only,omitempty"`

	// (String)
	TLS13 *string `json:"tls13,omitempty" tf:"tls_1_3,omitempty"`

	// (String)
	TLSClientAuth *string `json:"tlsClientAuth,omitempty" tf:"tls_client_auth,omitempty"`

	// (String)
	TrueClientIPHeader *string `json:"trueClientIpHeader,omitempty" tf:"true_client_ip_header,omitempty"`

	// (String)
	UniversalSSL *string `json:"universalSsl,omitempty" tf:"universal_ssl,omitempty"`

	// (String)
	VisitorIP *string `json:"visitorIp,omitempty" tf:"visitor_ip,omitempty"`

	// (String)
	Waf *string `json:"waf,omitempty" tf:"waf,omitempty"`

	// (String)
	Webp *string `json:"webp,omitempty" tf:"webp,omitempty"`

	// (String)
	Websockets *string `json:"websockets,omitempty" tf:"websockets,omitempty"`

	// (String)
	ZeroRtt *string `json:"zeroRtt,omitempty" tf:"zero_rtt,omitempty"`
}

type SettingsOverrideInitParameters struct {

	// (Block List, Max: 1) (see below for nested schema)
	Settings []SettingsInitParameters `json:"settings,omitempty" tf:"settings,omitempty"`
}

type SettingsOverrideObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of Object) (see below for nested schema)
	InitialSettings []InitialSettingsObservation `json:"initialSettings,omitempty" tf:"initial_settings,omitempty"`

	// (String)
	InitialSettingsReadAt *string `json:"initialSettingsReadAt,omitempty" tf:"initial_settings_read_at,omitempty"`

	// (List of String)
	ReadonlySettings []*string `json:"readonlySettings,omitempty" tf:"readonly_settings,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	Settings []SettingsObservation `json:"settings,omitempty" tf:"settings,omitempty"`

	// (String) The zone identifier to target for the resource. Modifying this attribute will force creation of a new resource.
	// The zone identifier to target for the resource. **Modifying this attribute will force creation of a new resource.**
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// (String)
	ZoneStatus *string `json:"zoneStatus,omitempty" tf:"zone_status,omitempty"`

	// (String)
	ZoneType *string `json:"zoneType,omitempty" tf:"zone_type,omitempty"`
}

type SettingsOverrideParameters struct {

	// (Block List, Max: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Settings []SettingsParameters `json:"settings,omitempty" tf:"settings,omitempty"`

	// (String) The zone identifier to target for the resource. Modifying this attribute will force creation of a new resource.
	// The zone identifier to target for the resource. **Modifying this attribute will force creation of a new resource.**
	// +crossplane:generate:reference:type=Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type SettingsParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	AlwaysOnline *string `json:"alwaysOnline,omitempty" tf:"always_online,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	AlwaysUseHTTPS *string `json:"alwaysUseHttps,omitempty" tf:"always_use_https,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	AutomaticHTTPSRewrites *string `json:"automaticHttpsRewrites,omitempty" tf:"automatic_https_rewrites,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	BinaryAst *string `json:"binaryAst,omitempty" tf:"binary_ast,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Brotli *string `json:"brotli,omitempty" tf:"brotli,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	BrowserCacheTTL *float64 `json:"browserCacheTtl,omitempty" tf:"browser_cache_ttl,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	BrowserCheck *string `json:"browserCheck,omitempty" tf:"browser_check,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	CacheLevel *string `json:"cacheLevel,omitempty" tf:"cache_level,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	ChallengeTTL *float64 `json:"challengeTtl,omitempty" tf:"challenge_ttl,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	Ciphers []*string `json:"ciphers,omitempty" tf:"ciphers,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	CnameFlattening *string `json:"cnameFlattening,omitempty" tf:"cname_flattening,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	DevelopmentMode *string `json:"developmentMode,omitempty" tf:"development_mode,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	EarlyHints *string `json:"earlyHints,omitempty" tf:"early_hints,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	EmailObfuscation *string `json:"emailObfuscation,omitempty" tf:"email_obfuscation,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	FilterLogsToCloudflare *string `json:"filterLogsToCloudflare,omitempty" tf:"filter_logs_to_cloudflare,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Fonts *string `json:"fonts,omitempty" tf:"fonts,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	H2Prioritization *string `json:"h2Prioritization,omitempty" tf:"h2_prioritization,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	HotlinkProtection *string `json:"hotlinkProtection,omitempty" tf:"hotlink_protection,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Http2 *string `json:"http2,omitempty" tf:"http2,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Http3 *string `json:"http3,omitempty" tf:"http3,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	IPGeolocation *string `json:"ipGeolocation,omitempty" tf:"ip_geolocation,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	IPv6 *string `json:"ipv6,omitempty" tf:"ipv6,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	ImageResizing *string `json:"imageResizing,omitempty" tf:"image_resizing,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	LogToCloudflare *string `json:"logToCloudflare,omitempty" tf:"log_to_cloudflare,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	MaxUpload *float64 `json:"maxUpload,omitempty" tf:"max_upload,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	MinTLSVersion *string `json:"minTlsVersion,omitempty" tf:"min_tls_version,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Minify []SettingsMinifyParameters `json:"minify,omitempty" tf:"minify,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Mirage *string `json:"mirage,omitempty" tf:"mirage,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	MobileRedirect []SettingsMobileRedirectParameters `json:"mobileRedirect,omitempty" tf:"mobile_redirect,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	OpportunisticEncryption *string `json:"opportunisticEncryption,omitempty" tf:"opportunistic_encryption,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	OpportunisticOnion *string `json:"opportunisticOnion,omitempty" tf:"opportunistic_onion,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	OrangeToOrange *string `json:"orangeToOrange,omitempty" tf:"orange_to_orange,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	OriginErrorPagePassThru *string `json:"originErrorPagePassThru,omitempty" tf:"origin_error_page_pass_thru,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	OriginMaxHTTPVersion *string `json:"originMaxHttpVersion,omitempty" tf:"origin_max_http_version,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Polish *string `json:"polish,omitempty" tf:"polish,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	PrefetchPreload *string `json:"prefetchPreload,omitempty" tf:"prefetch_preload,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	PrivacyPass *string `json:"privacyPass,omitempty" tf:"privacy_pass,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	ProxyReadTimeout *string `json:"proxyReadTimeout,omitempty" tf:"proxy_read_timeout,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	PseudoIPv4 *string `json:"pseudoIpv4,omitempty" tf:"pseudo_ipv4,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	ResponseBuffering *string `json:"responseBuffering,omitempty" tf:"response_buffering,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	RocketLoader *string `json:"rocketLoader,omitempty" tf:"rocket_loader,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	SSL *string `json:"ssl,omitempty" tf:"ssl,omitempty"`

	// (Block List, Max: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	SecurityHeader []SettingsSecurityHeaderParameters `json:"securityHeader,omitempty" tf:"security_header,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	SecurityLevel *string `json:"securityLevel,omitempty" tf:"security_level,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	ServerSideExclude *string `json:"serverSideExclude,omitempty" tf:"server_side_exclude,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	SortQueryStringForCache *string `json:"sortQueryStringForCache,omitempty" tf:"sort_query_string_for_cache,omitempty"`

	// (String, Deprecated)
	// +kubebuilder:validation:Optional
	TLS12Only *string `json:"tls12Only,omitempty" tf:"tls_1_2_only,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	TLS13 *string `json:"tls13,omitempty" tf:"tls_1_3,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	TLSClientAuth *string `json:"tlsClientAuth,omitempty" tf:"tls_client_auth,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	TrueClientIPHeader *string `json:"trueClientIpHeader,omitempty" tf:"true_client_ip_header,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	UniversalSSL *string `json:"universalSsl,omitempty" tf:"universal_ssl,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	VisitorIP *string `json:"visitorIp,omitempty" tf:"visitor_ip,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Waf *string `json:"waf,omitempty" tf:"waf,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Webp *string `json:"webp,omitempty" tf:"webp,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Websockets *string `json:"websockets,omitempty" tf:"websockets,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	ZeroRtt *string `json:"zeroRtt,omitempty" tf:"zero_rtt,omitempty"`
}

type SettingsSecurityHeaderInitParameters struct {

	// (Boolean)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean)
	IncludeSubdomains *bool `json:"includeSubdomains,omitempty" tf:"include_subdomains,omitempty"`

	// (Number)
	MaxAge *float64 `json:"maxAge,omitempty" tf:"max_age,omitempty"`

	// (Boolean)
	Nosniff *bool `json:"nosniff,omitempty" tf:"nosniff,omitempty"`

	// (Boolean)
	Preload *bool `json:"preload,omitempty" tf:"preload,omitempty"`
}

type SettingsSecurityHeaderObservation struct {

	// (Boolean)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean)
	IncludeSubdomains *bool `json:"includeSubdomains,omitempty" tf:"include_subdomains,omitempty"`

	// (Number)
	MaxAge *float64 `json:"maxAge,omitempty" tf:"max_age,omitempty"`

	// (Boolean)
	Nosniff *bool `json:"nosniff,omitempty" tf:"nosniff,omitempty"`

	// (Boolean)
	Preload *bool `json:"preload,omitempty" tf:"preload,omitempty"`
}

type SettingsSecurityHeaderParameters struct {

	// (Boolean)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	IncludeSubdomains *bool `json:"includeSubdomains,omitempty" tf:"include_subdomains,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	MaxAge *float64 `json:"maxAge,omitempty" tf:"max_age,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Nosniff *bool `json:"nosniff,omitempty" tf:"nosniff,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Preload *bool `json:"preload,omitempty" tf:"preload,omitempty"`
}

// SettingsOverrideSpec defines the desired state of SettingsOverride
type SettingsOverrideSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SettingsOverrideParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SettingsOverrideInitParameters `json:"initProvider,omitempty"`
}

// SettingsOverrideStatus defines the observed state of SettingsOverride.
type SettingsOverrideStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SettingsOverrideObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// SettingsOverride is the Schema for the SettingsOverrides API. Provides a resource which customizes Cloudflare zone settings.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type SettingsOverride struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SettingsOverrideSpec   `json:"spec"`
	Status            SettingsOverrideStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SettingsOverrideList contains a list of SettingsOverrides
type SettingsOverrideList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SettingsOverride `json:"items"`
}

// Repository type metadata.
var (
	SettingsOverride_Kind             = "SettingsOverride"
	SettingsOverride_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SettingsOverride_Kind}.String()
	SettingsOverride_KindAPIVersion   = SettingsOverride_Kind + "." + CRDGroupVersion.String()
	SettingsOverride_GroupVersionKind = CRDGroupVersion.WithKind(SettingsOverride_Kind)
)

func init() {
	SchemeBuilder.Register(&SettingsOverride{}, &SettingsOverrideList{})
}
