// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ApplicationInitParameters struct {

	// (Boolean) When set to true, users can authenticate to this application using their WARP session. When set to false this application will always require direct IdP authentication. This setting always overrides the organization setting for WARP authentication.
	// When set to true, users can authenticate to this application using their WARP session. When set to false this application will always require direct IdP authentication. This setting always overrides the organization setting for WARP authentication.
	AllowAuthenticateViaWarp *bool `json:"allowAuthenticateViaWarp,omitempty" tf:"allow_authenticate_via_warp,omitempty"`

	// (Set of String) The identity providers selected for the application.
	// The identity providers selected for the application.
	AllowedIdps []*string `json:"allowedIdps,omitempty" tf:"allowed_idps,omitempty"`

	// (String) The logo URL of the app launcher.
	// The logo URL of the app launcher.
	AppLauncherLogoURL *string `json:"appLauncherLogoUrl,omitempty" tf:"app_launcher_logo_url,omitempty"`

	// (Boolean) Option to show/hide applications in App Launcher. Defaults to true.
	// Option to show/hide applications in App Launcher. Defaults to `true`.
	AppLauncherVisible *bool `json:"appLauncherVisible,omitempty" tf:"app_launcher_visible,omitempty"`

	// (Boolean) Option to skip identity provider selection if only one is configured in allowed_idps. Defaults to false.
	// Option to skip identity provider selection if only one is configured in `allowed_idps`. Defaults to `false`.
	AutoRedirectToIdentity *bool `json:"autoRedirectToIdentity,omitempty" tf:"auto_redirect_to_identity,omitempty"`

	// (String) The background color of the app launcher.
	// The background color of the app launcher.
	BgColor *string `json:"bgColor,omitempty" tf:"bg_color,omitempty"`

	// (Block List) CORS configuration for the Access Application. See below for reference structure. (see below for nested schema)
	// CORS configuration for the Access Application. See below for reference structure.
	CorsHeaders []CorsHeadersInitParameters `json:"corsHeaders,omitempty" tf:"cors_headers,omitempty"`

	// (String) Option that returns a custom error message when a user is denied access to the application.
	// Option that returns a custom error message when a user is denied access to the application.
	CustomDenyMessage *string `json:"customDenyMessage,omitempty" tf:"custom_deny_message,omitempty"`

	// (String) Option that redirects to a custom URL when a user is denied access to the application via identity based rules.
	// Option that redirects to a custom URL when a user is denied access to the application via identity based rules.
	CustomDenyURL *string `json:"customDenyUrl,omitempty" tf:"custom_deny_url,omitempty"`

	// (String) Option that redirects to a custom URL when a user is denied access to the application via non identity rules.
	// Option that redirects to a custom URL when a user is denied access to the application via non identity rules.
	CustomNonIdentityDenyURL *string `json:"customNonIdentityDenyUrl,omitempty" tf:"custom_non_identity_deny_url,omitempty"`

	// (Set of String) The custom pages selected for the application.
	// The custom pages selected for the application.
	CustomPages []*string `json:"customPages,omitempty" tf:"custom_pages,omitempty"`

	// (String) The primary hostname and path that Access will secure. If the app is visible in the App Launcher dashboard, this is the domain that will be displayed.
	// The primary hostname and path that Access will secure. If the app is visible in the App Launcher dashboard, this is the domain that will be displayed.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (Boolean) Option to provide increased security against compromised authorization tokens and CSRF attacks by requiring an additional "binding" cookie on requests. Defaults to false.
	// Option to provide increased security against compromised authorization tokens and CSRF attacks by requiring an additional "binding" cookie on requests. Defaults to `false`.
	EnableBindingCookie *bool `json:"enableBindingCookie,omitempty" tf:"enable_binding_cookie,omitempty"`

	// (Block Set) The footer links of the app launcher. (see below for nested schema)
	// The footer links of the app launcher.
	FooterLinks []FooterLinksInitParameters `json:"footerLinks,omitempty" tf:"footer_links,omitempty"`

	// (Boolean) Option to add the HttpOnly cookie flag to access tokens.
	// Option to add the `HttpOnly` cookie flag to access tokens.
	HTTPOnlyCookieAttribute *bool `json:"httpOnlyCookieAttribute,omitempty" tf:"http_only_cookie_attribute,omitempty"`

	// (String) The background color of the header bar in the app launcher.
	// The background color of the header bar in the app launcher.
	HeaderBgColor *string `json:"headerBgColor,omitempty" tf:"header_bg_color,omitempty"`

	// (Block List, Max: 1) The landing page design of the app launcher. (see below for nested schema)
	// The landing page design of the app launcher.
	LandingPageDesign []LandingPageDesignInitParameters `json:"landingPageDesign,omitempty" tf:"landing_page_design,omitempty"`

	// (String) Image URL for the logo shown in the app launcher dashboard.
	// Image URL for the logo shown in the app launcher dashboard.
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// (String) Friendly name of the Access Application.
	// Friendly name of the Access Application.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Allows options preflight requests to bypass Access authentication and go directly to the origin. Cannot turn on if cors_headers is set. Defaults to false.
	// Allows options preflight requests to bypass Access authentication and go directly to the origin. Cannot turn on if cors_headers is set. Defaults to `false`.
	OptionsPreflightBypass *bool `json:"optionsPreflightBypass,omitempty" tf:"options_preflight_bypass,omitempty"`

	// (Block List, Max: 1) SaaS configuration for the Access Application. (see below for nested schema)
	// SaaS configuration for the Access Application.
	SaasApp []SaasAppInitParameters `json:"saasApp,omitempty" tf:"saas_app,omitempty"`

	// site cookie setting for access tokens. Available values: none, lax, strict.
	// Defines the same-site cookie setting for access tokens. Available values: `none`, `lax`, `strict`.
	SameSiteCookieAttribute *string `json:"sameSiteCookieAttribute,omitempty" tf:"same_site_cookie_attribute,omitempty"`

	// (Set of String) List of domains that access will secure. Only present for self_hosted, vnc, and ssh applications. Always includes the value set as domain.
	// List of domains that access will secure. Only present for self_hosted, vnc, and ssh applications. Always includes the value set as `domain`.
	SelfHostedDomains []*string `json:"selfHostedDomains,omitempty" tf:"self_hosted_domains,omitempty"`

	// (Boolean) Option to return a 401 status code in service authentication rules on failed requests. Defaults to false.
	// Option to return a 401 status code in service authentication rules on failed requests. Defaults to `false`.
	ServiceAuth401Redirect *bool `json:"serviceAuth401Redirect,omitempty" tf:"service_auth_401_redirect,omitempty"`

	// authorise. Must be in the format 48h or 2h45m. Defaults to 24h.
	// How often a user will be forced to re-authorise. Must be in the format `48h` or `2h45m`. Defaults to `24h`.
	SessionDuration *string `json:"sessionDuration,omitempty" tf:"session_duration,omitempty"`

	// (Boolean) Option to skip the authorization interstitial when using the CLI. Defaults to false.
	// Option to skip the authorization interstitial when using the CLI. Defaults to `false`.
	SkipInterstitial *bool `json:"skipInterstitial,omitempty" tf:"skip_interstitial,omitempty"`

	// (Set of String) The itags associated with the application.
	// The itags associated with the application.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) The application type. Available values: app_launcher, bookmark, biso, dash_sso, saas, self_hosted, ssh, vnc, warp. Defaults to self_hosted.
	// The application type. Available values: `app_launcher`, `bookmark`, `biso`, `dash_sso`, `saas`, `self_hosted`, `ssh`, `vnc`, `warp`. Defaults to `self_hosted`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ApplicationObservation struct {

	// (String) The account identifier to target for the resource. Conflicts with zone_id.
	// The account identifier to target for the resource. Conflicts with `zone_id`.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Boolean) When set to true, users can authenticate to this application using their WARP session. When set to false this application will always require direct IdP authentication. This setting always overrides the organization setting for WARP authentication.
	// When set to true, users can authenticate to this application using their WARP session. When set to false this application will always require direct IdP authentication. This setting always overrides the organization setting for WARP authentication.
	AllowAuthenticateViaWarp *bool `json:"allowAuthenticateViaWarp,omitempty" tf:"allow_authenticate_via_warp,omitempty"`

	// (Set of String) The identity providers selected for the application.
	// The identity providers selected for the application.
	AllowedIdps []*string `json:"allowedIdps,omitempty" tf:"allowed_idps,omitempty"`

	// (String) The logo URL of the app launcher.
	// The logo URL of the app launcher.
	AppLauncherLogoURL *string `json:"appLauncherLogoUrl,omitempty" tf:"app_launcher_logo_url,omitempty"`

	// (Boolean) Option to show/hide applications in App Launcher. Defaults to true.
	// Option to show/hide applications in App Launcher. Defaults to `true`.
	AppLauncherVisible *bool `json:"appLauncherVisible,omitempty" tf:"app_launcher_visible,omitempty"`

	// (String) Application Audience (AUD) Tag of the application.
	// Application Audience (AUD) Tag of the application.
	Aud *string `json:"aud,omitempty" tf:"aud,omitempty"`

	// (Boolean) Option to skip identity provider selection if only one is configured in allowed_idps. Defaults to false.
	// Option to skip identity provider selection if only one is configured in `allowed_idps`. Defaults to `false`.
	AutoRedirectToIdentity *bool `json:"autoRedirectToIdentity,omitempty" tf:"auto_redirect_to_identity,omitempty"`

	// (String) The background color of the app launcher.
	// The background color of the app launcher.
	BgColor *string `json:"bgColor,omitempty" tf:"bg_color,omitempty"`

	// (Block List) CORS configuration for the Access Application. See below for reference structure. (see below for nested schema)
	// CORS configuration for the Access Application. See below for reference structure.
	CorsHeaders []CorsHeadersObservation `json:"corsHeaders,omitempty" tf:"cors_headers,omitempty"`

	// (String) Option that returns a custom error message when a user is denied access to the application.
	// Option that returns a custom error message when a user is denied access to the application.
	CustomDenyMessage *string `json:"customDenyMessage,omitempty" tf:"custom_deny_message,omitempty"`

	// (String) Option that redirects to a custom URL when a user is denied access to the application via identity based rules.
	// Option that redirects to a custom URL when a user is denied access to the application via identity based rules.
	CustomDenyURL *string `json:"customDenyUrl,omitempty" tf:"custom_deny_url,omitempty"`

	// (String) Option that redirects to a custom URL when a user is denied access to the application via non identity rules.
	// Option that redirects to a custom URL when a user is denied access to the application via non identity rules.
	CustomNonIdentityDenyURL *string `json:"customNonIdentityDenyUrl,omitempty" tf:"custom_non_identity_deny_url,omitempty"`

	// (Set of String) The custom pages selected for the application.
	// The custom pages selected for the application.
	CustomPages []*string `json:"customPages,omitempty" tf:"custom_pages,omitempty"`

	// (String) The primary hostname and path that Access will secure. If the app is visible in the App Launcher dashboard, this is the domain that will be displayed.
	// The primary hostname and path that Access will secure. If the app is visible in the App Launcher dashboard, this is the domain that will be displayed.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (Boolean) Option to provide increased security against compromised authorization tokens and CSRF attacks by requiring an additional "binding" cookie on requests. Defaults to false.
	// Option to provide increased security against compromised authorization tokens and CSRF attacks by requiring an additional "binding" cookie on requests. Defaults to `false`.
	EnableBindingCookie *bool `json:"enableBindingCookie,omitempty" tf:"enable_binding_cookie,omitempty"`

	// (Block Set) The footer links of the app launcher. (see below for nested schema)
	// The footer links of the app launcher.
	FooterLinks []FooterLinksObservation `json:"footerLinks,omitempty" tf:"footer_links,omitempty"`

	// (Boolean) Option to add the HttpOnly cookie flag to access tokens.
	// Option to add the `HttpOnly` cookie flag to access tokens.
	HTTPOnlyCookieAttribute *bool `json:"httpOnlyCookieAttribute,omitempty" tf:"http_only_cookie_attribute,omitempty"`

	// (String) The background color of the header bar in the app launcher.
	// The background color of the header bar in the app launcher.
	HeaderBgColor *string `json:"headerBgColor,omitempty" tf:"header_bg_color,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Block List, Max: 1) The landing page design of the app launcher. (see below for nested schema)
	// The landing page design of the app launcher.
	LandingPageDesign []LandingPageDesignObservation `json:"landingPageDesign,omitempty" tf:"landing_page_design,omitempty"`

	// (String) Image URL for the logo shown in the app launcher dashboard.
	// Image URL for the logo shown in the app launcher dashboard.
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// (String) Friendly name of the Access Application.
	// Friendly name of the Access Application.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Allows options preflight requests to bypass Access authentication and go directly to the origin. Cannot turn on if cors_headers is set. Defaults to false.
	// Allows options preflight requests to bypass Access authentication and go directly to the origin. Cannot turn on if cors_headers is set. Defaults to `false`.
	OptionsPreflightBypass *bool `json:"optionsPreflightBypass,omitempty" tf:"options_preflight_bypass,omitempty"`

	// (Block List, Max: 1) SaaS configuration for the Access Application. (see below for nested schema)
	// SaaS configuration for the Access Application.
	SaasApp []SaasAppObservation `json:"saasApp,omitempty" tf:"saas_app,omitempty"`

	// site cookie setting for access tokens. Available values: none, lax, strict.
	// Defines the same-site cookie setting for access tokens. Available values: `none`, `lax`, `strict`.
	SameSiteCookieAttribute *string `json:"sameSiteCookieAttribute,omitempty" tf:"same_site_cookie_attribute,omitempty"`

	// (Set of String) List of domains that access will secure. Only present for self_hosted, vnc, and ssh applications. Always includes the value set as domain.
	// List of domains that access will secure. Only present for self_hosted, vnc, and ssh applications. Always includes the value set as `domain`.
	SelfHostedDomains []*string `json:"selfHostedDomains,omitempty" tf:"self_hosted_domains,omitempty"`

	// (Boolean) Option to return a 401 status code in service authentication rules on failed requests. Defaults to false.
	// Option to return a 401 status code in service authentication rules on failed requests. Defaults to `false`.
	ServiceAuth401Redirect *bool `json:"serviceAuth401Redirect,omitempty" tf:"service_auth_401_redirect,omitempty"`

	// authorise. Must be in the format 48h or 2h45m. Defaults to 24h.
	// How often a user will be forced to re-authorise. Must be in the format `48h` or `2h45m`. Defaults to `24h`.
	SessionDuration *string `json:"sessionDuration,omitempty" tf:"session_duration,omitempty"`

	// (Boolean) Option to skip the authorization interstitial when using the CLI. Defaults to false.
	// Option to skip the authorization interstitial when using the CLI. Defaults to `false`.
	SkipInterstitial *bool `json:"skipInterstitial,omitempty" tf:"skip_interstitial,omitempty"`

	// (Set of String) The itags associated with the application.
	// The itags associated with the application.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) The application type. Available values: app_launcher, bookmark, biso, dash_sso, saas, self_hosted, ssh, vnc, warp. Defaults to self_hosted.
	// The application type. Available values: `app_launcher`, `bookmark`, `biso`, `dash_sso`, `saas`, `self_hosted`, `ssh`, `vnc`, `warp`. Defaults to `self_hosted`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The zone identifier to target for the resource. Conflicts with account_id.
	// The zone identifier to target for the resource. Conflicts with `account_id`.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ApplicationParameters struct {

	// (String) The account identifier to target for the resource. Conflicts with zone_id.
	// The account identifier to target for the resource. Conflicts with `zone_id`.
	// +crossplane:generate:reference:type=github.com/milkpirate/provider-cloudflare/apis/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (Boolean) When set to true, users can authenticate to this application using their WARP session. When set to false this application will always require direct IdP authentication. This setting always overrides the organization setting for WARP authentication.
	// When set to true, users can authenticate to this application using their WARP session. When set to false this application will always require direct IdP authentication. This setting always overrides the organization setting for WARP authentication.
	// +kubebuilder:validation:Optional
	AllowAuthenticateViaWarp *bool `json:"allowAuthenticateViaWarp,omitempty" tf:"allow_authenticate_via_warp,omitempty"`

	// (Set of String) The identity providers selected for the application.
	// The identity providers selected for the application.
	// +kubebuilder:validation:Optional
	AllowedIdps []*string `json:"allowedIdps,omitempty" tf:"allowed_idps,omitempty"`

	// (String) The logo URL of the app launcher.
	// The logo URL of the app launcher.
	// +kubebuilder:validation:Optional
	AppLauncherLogoURL *string `json:"appLauncherLogoUrl,omitempty" tf:"app_launcher_logo_url,omitempty"`

	// (Boolean) Option to show/hide applications in App Launcher. Defaults to true.
	// Option to show/hide applications in App Launcher. Defaults to `true`.
	// +kubebuilder:validation:Optional
	AppLauncherVisible *bool `json:"appLauncherVisible,omitempty" tf:"app_launcher_visible,omitempty"`

	// (Boolean) Option to skip identity provider selection if only one is configured in allowed_idps. Defaults to false.
	// Option to skip identity provider selection if only one is configured in `allowed_idps`. Defaults to `false`.
	// +kubebuilder:validation:Optional
	AutoRedirectToIdentity *bool `json:"autoRedirectToIdentity,omitempty" tf:"auto_redirect_to_identity,omitempty"`

	// (String) The background color of the app launcher.
	// The background color of the app launcher.
	// +kubebuilder:validation:Optional
	BgColor *string `json:"bgColor,omitempty" tf:"bg_color,omitempty"`

	// (Block List) CORS configuration for the Access Application. See below for reference structure. (see below for nested schema)
	// CORS configuration for the Access Application. See below for reference structure.
	// +kubebuilder:validation:Optional
	CorsHeaders []CorsHeadersParameters `json:"corsHeaders,omitempty" tf:"cors_headers,omitempty"`

	// (String) Option that returns a custom error message when a user is denied access to the application.
	// Option that returns a custom error message when a user is denied access to the application.
	// +kubebuilder:validation:Optional
	CustomDenyMessage *string `json:"customDenyMessage,omitempty" tf:"custom_deny_message,omitempty"`

	// (String) Option that redirects to a custom URL when a user is denied access to the application via identity based rules.
	// Option that redirects to a custom URL when a user is denied access to the application via identity based rules.
	// +kubebuilder:validation:Optional
	CustomDenyURL *string `json:"customDenyUrl,omitempty" tf:"custom_deny_url,omitempty"`

	// (String) Option that redirects to a custom URL when a user is denied access to the application via non identity rules.
	// Option that redirects to a custom URL when a user is denied access to the application via non identity rules.
	// +kubebuilder:validation:Optional
	CustomNonIdentityDenyURL *string `json:"customNonIdentityDenyUrl,omitempty" tf:"custom_non_identity_deny_url,omitempty"`

	// (Set of String) The custom pages selected for the application.
	// The custom pages selected for the application.
	// +kubebuilder:validation:Optional
	CustomPages []*string `json:"customPages,omitempty" tf:"custom_pages,omitempty"`

	// (String) The primary hostname and path that Access will secure. If the app is visible in the App Launcher dashboard, this is the domain that will be displayed.
	// The primary hostname and path that Access will secure. If the app is visible in the App Launcher dashboard, this is the domain that will be displayed.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// (Boolean) Option to provide increased security against compromised authorization tokens and CSRF attacks by requiring an additional "binding" cookie on requests. Defaults to false.
	// Option to provide increased security against compromised authorization tokens and CSRF attacks by requiring an additional "binding" cookie on requests. Defaults to `false`.
	// +kubebuilder:validation:Optional
	EnableBindingCookie *bool `json:"enableBindingCookie,omitempty" tf:"enable_binding_cookie,omitempty"`

	// (Block Set) The footer links of the app launcher. (see below for nested schema)
	// The footer links of the app launcher.
	// +kubebuilder:validation:Optional
	FooterLinks []FooterLinksParameters `json:"footerLinks,omitempty" tf:"footer_links,omitempty"`

	// (Boolean) Option to add the HttpOnly cookie flag to access tokens.
	// Option to add the `HttpOnly` cookie flag to access tokens.
	// +kubebuilder:validation:Optional
	HTTPOnlyCookieAttribute *bool `json:"httpOnlyCookieAttribute,omitempty" tf:"http_only_cookie_attribute,omitempty"`

	// (String) The background color of the header bar in the app launcher.
	// The background color of the header bar in the app launcher.
	// +kubebuilder:validation:Optional
	HeaderBgColor *string `json:"headerBgColor,omitempty" tf:"header_bg_color,omitempty"`

	// (Block List, Max: 1) The landing page design of the app launcher. (see below for nested schema)
	// The landing page design of the app launcher.
	// +kubebuilder:validation:Optional
	LandingPageDesign []LandingPageDesignParameters `json:"landingPageDesign,omitempty" tf:"landing_page_design,omitempty"`

	// (String) Image URL for the logo shown in the app launcher dashboard.
	// Image URL for the logo shown in the app launcher dashboard.
	// +kubebuilder:validation:Optional
	LogoURL *string `json:"logoUrl,omitempty" tf:"logo_url,omitempty"`

	// (String) Friendly name of the Access Application.
	// Friendly name of the Access Application.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Allows options preflight requests to bypass Access authentication and go directly to the origin. Cannot turn on if cors_headers is set. Defaults to false.
	// Allows options preflight requests to bypass Access authentication and go directly to the origin. Cannot turn on if cors_headers is set. Defaults to `false`.
	// +kubebuilder:validation:Optional
	OptionsPreflightBypass *bool `json:"optionsPreflightBypass,omitempty" tf:"options_preflight_bypass,omitempty"`

	// (Block List, Max: 1) SaaS configuration for the Access Application. (see below for nested schema)
	// SaaS configuration for the Access Application.
	// +kubebuilder:validation:Optional
	SaasApp []SaasAppParameters `json:"saasApp,omitempty" tf:"saas_app,omitempty"`

	// site cookie setting for access tokens. Available values: none, lax, strict.
	// Defines the same-site cookie setting for access tokens. Available values: `none`, `lax`, `strict`.
	// +kubebuilder:validation:Optional
	SameSiteCookieAttribute *string `json:"sameSiteCookieAttribute,omitempty" tf:"same_site_cookie_attribute,omitempty"`

	// (Set of String) List of domains that access will secure. Only present for self_hosted, vnc, and ssh applications. Always includes the value set as domain.
	// List of domains that access will secure. Only present for self_hosted, vnc, and ssh applications. Always includes the value set as `domain`.
	// +kubebuilder:validation:Optional
	SelfHostedDomains []*string `json:"selfHostedDomains,omitempty" tf:"self_hosted_domains,omitempty"`

	// (Boolean) Option to return a 401 status code in service authentication rules on failed requests. Defaults to false.
	// Option to return a 401 status code in service authentication rules on failed requests. Defaults to `false`.
	// +kubebuilder:validation:Optional
	ServiceAuth401Redirect *bool `json:"serviceAuth401Redirect,omitempty" tf:"service_auth_401_redirect,omitempty"`

	// authorise. Must be in the format 48h or 2h45m. Defaults to 24h.
	// How often a user will be forced to re-authorise. Must be in the format `48h` or `2h45m`. Defaults to `24h`.
	// +kubebuilder:validation:Optional
	SessionDuration *string `json:"sessionDuration,omitempty" tf:"session_duration,omitempty"`

	// (Boolean) Option to skip the authorization interstitial when using the CLI. Defaults to false.
	// Option to skip the authorization interstitial when using the CLI. Defaults to `false`.
	// +kubebuilder:validation:Optional
	SkipInterstitial *bool `json:"skipInterstitial,omitempty" tf:"skip_interstitial,omitempty"`

	// (Set of String) The itags associated with the application.
	// The itags associated with the application.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// (String) The application type. Available values: app_launcher, bookmark, biso, dash_sso, saas, self_hosted, ssh, vnc, warp. Defaults to self_hosted.
	// The application type. Available values: `app_launcher`, `bookmark`, `biso`, `dash_sso`, `saas`, `self_hosted`, `ssh`, `vnc`, `warp`. Defaults to `self_hosted`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) The zone identifier to target for the resource. Conflicts with account_id.
	// The zone identifier to target for the resource. Conflicts with `account_id`.
	// +crossplane:generate:reference:type=github.com/milkpirate/provider-cloudflare/apis/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type CorsHeadersInitParameters struct {

	// (Boolean) Value to determine whether all HTTP headers are exposed.
	// Value to determine whether all HTTP headers are exposed.
	AllowAllHeaders *bool `json:"allowAllHeaders,omitempty" tf:"allow_all_headers,omitempty"`

	// (Boolean) Value to determine whether all methods are exposed.
	// Value to determine whether all methods are exposed.
	AllowAllMethods *bool `json:"allowAllMethods,omitempty" tf:"allow_all_methods,omitempty"`

	// (Boolean) Value to determine whether all origins are permitted to make CORS requests.
	// Value to determine whether all origins are permitted to make CORS requests.
	AllowAllOrigins *bool `json:"allowAllOrigins,omitempty" tf:"allow_all_origins,omitempty"`

	// (Boolean) Value to determine if credentials (cookies, authorization headers, or TLS client certificates) are included with requests.
	// Value to determine if credentials (cookies, authorization headers, or TLS client certificates) are included with requests.
	AllowCredentials *bool `json:"allowCredentials,omitempty" tf:"allow_credentials,omitempty"`

	// (Set of String) List of HTTP headers to expose via CORS.
	// List of HTTP headers to expose via CORS.
	AllowedHeaders []*string `json:"allowedHeaders,omitempty" tf:"allowed_headers,omitempty"`

	// (Set of String) List of methods to expose via CORS.
	// List of methods to expose via CORS.
	AllowedMethods []*string `json:"allowedMethods,omitempty" tf:"allowed_methods,omitempty"`

	// (Set of String) List of origins permitted to make CORS requests.
	// List of origins permitted to make CORS requests.
	AllowedOrigins []*string `json:"allowedOrigins,omitempty" tf:"allowed_origins,omitempty"`

	// (Number) The maximum time a preflight request will be cached.
	// The maximum time a preflight request will be cached.
	MaxAge *float64 `json:"maxAge,omitempty" tf:"max_age,omitempty"`
}

type CorsHeadersObservation struct {

	// (Boolean) Value to determine whether all HTTP headers are exposed.
	// Value to determine whether all HTTP headers are exposed.
	AllowAllHeaders *bool `json:"allowAllHeaders,omitempty" tf:"allow_all_headers,omitempty"`

	// (Boolean) Value to determine whether all methods are exposed.
	// Value to determine whether all methods are exposed.
	AllowAllMethods *bool `json:"allowAllMethods,omitempty" tf:"allow_all_methods,omitempty"`

	// (Boolean) Value to determine whether all origins are permitted to make CORS requests.
	// Value to determine whether all origins are permitted to make CORS requests.
	AllowAllOrigins *bool `json:"allowAllOrigins,omitempty" tf:"allow_all_origins,omitempty"`

	// (Boolean) Value to determine if credentials (cookies, authorization headers, or TLS client certificates) are included with requests.
	// Value to determine if credentials (cookies, authorization headers, or TLS client certificates) are included with requests.
	AllowCredentials *bool `json:"allowCredentials,omitempty" tf:"allow_credentials,omitempty"`

	// (Set of String) List of HTTP headers to expose via CORS.
	// List of HTTP headers to expose via CORS.
	AllowedHeaders []*string `json:"allowedHeaders,omitempty" tf:"allowed_headers,omitempty"`

	// (Set of String) List of methods to expose via CORS.
	// List of methods to expose via CORS.
	AllowedMethods []*string `json:"allowedMethods,omitempty" tf:"allowed_methods,omitempty"`

	// (Set of String) List of origins permitted to make CORS requests.
	// List of origins permitted to make CORS requests.
	AllowedOrigins []*string `json:"allowedOrigins,omitempty" tf:"allowed_origins,omitempty"`

	// (Number) The maximum time a preflight request will be cached.
	// The maximum time a preflight request will be cached.
	MaxAge *float64 `json:"maxAge,omitempty" tf:"max_age,omitempty"`
}

type CorsHeadersParameters struct {

	// (Boolean) Value to determine whether all HTTP headers are exposed.
	// Value to determine whether all HTTP headers are exposed.
	// +kubebuilder:validation:Optional
	AllowAllHeaders *bool `json:"allowAllHeaders,omitempty" tf:"allow_all_headers,omitempty"`

	// (Boolean) Value to determine whether all methods are exposed.
	// Value to determine whether all methods are exposed.
	// +kubebuilder:validation:Optional
	AllowAllMethods *bool `json:"allowAllMethods,omitempty" tf:"allow_all_methods,omitempty"`

	// (Boolean) Value to determine whether all origins are permitted to make CORS requests.
	// Value to determine whether all origins are permitted to make CORS requests.
	// +kubebuilder:validation:Optional
	AllowAllOrigins *bool `json:"allowAllOrigins,omitempty" tf:"allow_all_origins,omitempty"`

	// (Boolean) Value to determine if credentials (cookies, authorization headers, or TLS client certificates) are included with requests.
	// Value to determine if credentials (cookies, authorization headers, or TLS client certificates) are included with requests.
	// +kubebuilder:validation:Optional
	AllowCredentials *bool `json:"allowCredentials,omitempty" tf:"allow_credentials,omitempty"`

	// (Set of String) List of HTTP headers to expose via CORS.
	// List of HTTP headers to expose via CORS.
	// +kubebuilder:validation:Optional
	AllowedHeaders []*string `json:"allowedHeaders,omitempty" tf:"allowed_headers,omitempty"`

	// (Set of String) List of methods to expose via CORS.
	// List of methods to expose via CORS.
	// +kubebuilder:validation:Optional
	AllowedMethods []*string `json:"allowedMethods,omitempty" tf:"allowed_methods,omitempty"`

	// (Set of String) List of origins permitted to make CORS requests.
	// List of origins permitted to make CORS requests.
	// +kubebuilder:validation:Optional
	AllowedOrigins []*string `json:"allowedOrigins,omitempty" tf:"allowed_origins,omitempty"`

	// (Number) The maximum time a preflight request will be cached.
	// The maximum time a preflight request will be cached.
	// +kubebuilder:validation:Optional
	MaxAge *float64 `json:"maxAge,omitempty" tf:"max_age,omitempty"`
}

type CustomAttributeInitParameters struct {

	// (String) A friendly name for the attribute as provided to the SaaS app.
	// A friendly name for the attribute as provided to the SaaS app.
	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	// (String) Friendly name of the Access Application.
	// The name of the attribute as provided to the SaaS app.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) A globally unique name for an identity or service provider.
	// A globally unique name for an identity or service provider.
	NameFormat *string `json:"nameFormat,omitempty" tf:"name_format,omitempty"`

	// (Boolean) True if the attribute must be always present.
	// True if the attribute must be always present.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// (Block List, Min: 1, Max: 1) (see below for nested schema)
	Source []SourceInitParameters `json:"source,omitempty" tf:"source,omitempty"`
}

type CustomAttributeObservation struct {

	// (String) A friendly name for the attribute as provided to the SaaS app.
	// A friendly name for the attribute as provided to the SaaS app.
	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	// (String) Friendly name of the Access Application.
	// The name of the attribute as provided to the SaaS app.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) A globally unique name for an identity or service provider.
	// A globally unique name for an identity or service provider.
	NameFormat *string `json:"nameFormat,omitempty" tf:"name_format,omitempty"`

	// (Boolean) True if the attribute must be always present.
	// True if the attribute must be always present.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// (Block List, Min: 1, Max: 1) (see below for nested schema)
	Source []SourceObservation `json:"source,omitempty" tf:"source,omitempty"`
}

type CustomAttributeParameters struct {

	// (String) A friendly name for the attribute as provided to the SaaS app.
	// A friendly name for the attribute as provided to the SaaS app.
	// +kubebuilder:validation:Optional
	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	// (String) Friendly name of the Access Application.
	// The name of the attribute as provided to the SaaS app.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) A globally unique name for an identity or service provider.
	// A globally unique name for an identity or service provider.
	// +kubebuilder:validation:Optional
	NameFormat *string `json:"nameFormat,omitempty" tf:"name_format,omitempty"`

	// (Boolean) True if the attribute must be always present.
	// True if the attribute must be always present.
	// +kubebuilder:validation:Optional
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// (Block List, Min: 1, Max: 1) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Source []SourceParameters `json:"source" tf:"source,omitempty"`
}

type FooterLinksInitParameters struct {

	// (String) Friendly name of the Access Application.
	// The name of the footer link.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The URL of the footer link.
	// The URL of the footer link.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type FooterLinksObservation struct {

	// (String) Friendly name of the Access Application.
	// The name of the footer link.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The URL of the footer link.
	// The URL of the footer link.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type FooterLinksParameters struct {

	// (String) Friendly name of the Access Application.
	// The name of the footer link.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The URL of the footer link.
	// The URL of the footer link.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type LandingPageDesignInitParameters struct {

	// (String) The button color of the landing page.
	// The button color of the landing page.
	ButtonColor *string `json:"buttonColor,omitempty" tf:"button_color,omitempty"`

	// (String) The button text color of the landing page.
	// The button text color of the landing page.
	ButtonTextColor *string `json:"buttonTextColor,omitempty" tf:"button_text_color,omitempty"`

	// (String) The URL of the image to be displayed in the landing page.
	// The URL of the image to be displayed in the landing page.
	ImageURL *string `json:"imageUrl,omitempty" tf:"image_url,omitempty"`

	// (String) The message of the landing page.
	// The message of the landing page.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// (String) The title of the landing page.
	// The title of the landing page.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type LandingPageDesignObservation struct {

	// (String) The button color of the landing page.
	// The button color of the landing page.
	ButtonColor *string `json:"buttonColor,omitempty" tf:"button_color,omitempty"`

	// (String) The button text color of the landing page.
	// The button text color of the landing page.
	ButtonTextColor *string `json:"buttonTextColor,omitempty" tf:"button_text_color,omitempty"`

	// (String) The URL of the image to be displayed in the landing page.
	// The URL of the image to be displayed in the landing page.
	ImageURL *string `json:"imageUrl,omitempty" tf:"image_url,omitempty"`

	// (String) The message of the landing page.
	// The message of the landing page.
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// (String) The title of the landing page.
	// The title of the landing page.
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type LandingPageDesignParameters struct {

	// (String) The button color of the landing page.
	// The button color of the landing page.
	// +kubebuilder:validation:Optional
	ButtonColor *string `json:"buttonColor,omitempty" tf:"button_color,omitempty"`

	// (String) The button text color of the landing page.
	// The button text color of the landing page.
	// +kubebuilder:validation:Optional
	ButtonTextColor *string `json:"buttonTextColor,omitempty" tf:"button_text_color,omitempty"`

	// (String) The URL of the image to be displayed in the landing page.
	// The URL of the image to be displayed in the landing page.
	// +kubebuilder:validation:Optional
	ImageURL *string `json:"imageUrl,omitempty" tf:"image_url,omitempty"`

	// (String) The message of the landing page.
	// The message of the landing page.
	// +kubebuilder:validation:Optional
	Message *string `json:"message,omitempty" tf:"message,omitempty"`

	// (String) The title of the landing page.
	// The title of the landing page.
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type SaasAppInitParameters struct {

	// (String) The URL where this applications tile redirects users.
	// The URL where this applications tile redirects users.
	AppLauncherURL *string `json:"appLauncherUrl,omitempty" tf:"app_launcher_url,omitempty"`

	// (String)
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String) The service provider's endpoint that is responsible for receiving and parsing a SAML assertion.
	// The service provider's endpoint that is responsible for receiving and parsing a SAML assertion.
	ConsumerServiceURL *string `json:"consumerServiceUrl,omitempty" tf:"consumer_service_url,omitempty"`

	// (Block List) Custom attribute mapped from IDPs. (see below for nested schema)
	// Custom attribute mapped from IDPs.
	CustomAttribute []CustomAttributeInitParameters `json:"customAttribute,omitempty" tf:"custom_attribute,omitempty"`

	// (String) The relay state used if not provided by the identity provider.
	// The relay state used if not provided by the identity provider.
	DefaultRelayState *string `json:"defaultRelayState,omitempty" tf:"default_relay_state,omitempty"`

	// (Set of String) The OIDC flows supported by this application.
	// The OIDC flows supported by this application.
	GrantTypes []*string `json:"grantTypes,omitempty" tf:"grant_types,omitempty"`

	// (String) A regex to filter Cloudflare groups returned in ID token and userinfo endpoint.
	// A regex to filter Cloudflare groups returned in ID token and userinfo endpoint.
	GroupFilterRegex *string `json:"groupFilterRegex,omitempty" tf:"group_filter_regex,omitempty"`

	// (String) The format of the name identifier sent to the SaaS application.
	// The format of the name identifier sent to the SaaS application.
	NameIDFormat *string `json:"nameIdFormat,omitempty" tf:"name_id_format,omitempty"`

	// (String) A JSONata expression that transforms an application's user identities into a NameID value for its SAML assertion. This expression should evaluate to a singular string. The output of this expression can override the name_id_format setting.
	// A [JSONata](https://jsonata.org/) expression that transforms an application's user identities into a NameID value for its SAML assertion. This expression should evaluate to a singular string. The output of this expression can override the `name_id_format` setting.
	NameIDTransformJsonata *string `json:"nameIdTransformJsonata,omitempty" tf:"name_id_transform_jsonata,omitempty"`

	// (Set of String) The permitted URL's for Cloudflare to return Authorization codes and Access/ID tokens.
	// The permitted URL's for Cloudflare to return Authorization codes and Access/ID tokens.
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`

	// (String) A JSONata expression that transforms an application's user identities into attribute assertions in the SAML response. The expression can transform id, email, name, and groups values. It can also transform fields listed in the saml_attributes or oidc_fields of the identity provider used to authenticate. The output of this expression must be a JSON object.
	// A [JSONata](https://jsonata.org/) expression that transforms an application's user identities into attribute assertions in the SAML response. The expression can transform id, email, name, and groups values. It can also transform fields listed in the saml_attributes or oidc_fields of the identity provider used to authenticate. The output of this expression must be a JSON object.
	SAMLAttributeTransformJsonata *string `json:"samlAttributeTransformJsonata,omitempty" tf:"saml_attribute_transform_jsonata,omitempty"`

	// (Set of String) Define the user information shared with access.
	// Define the user information shared with access.
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// (String) A globally unique name for an identity or service provider.
	// A globally unique name for an identity or service provider.
	SpEntityID *string `json:"spEntityId,omitempty" tf:"sp_entity_id,omitempty"`
}

type SaasAppObservation struct {

	// (String) The URL where this applications tile redirects users.
	// The URL where this applications tile redirects users.
	AppLauncherURL *string `json:"appLauncherUrl,omitempty" tf:"app_launcher_url,omitempty"`

	// (String)
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String) The application client id.
	// The application client id.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) The service provider's endpoint that is responsible for receiving and parsing a SAML assertion.
	// The service provider's endpoint that is responsible for receiving and parsing a SAML assertion.
	ConsumerServiceURL *string `json:"consumerServiceUrl,omitempty" tf:"consumer_service_url,omitempty"`

	// (Block List) Custom attribute mapped from IDPs. (see below for nested schema)
	// Custom attribute mapped from IDPs.
	CustomAttribute []CustomAttributeObservation `json:"customAttribute,omitempty" tf:"custom_attribute,omitempty"`

	// (String) The relay state used if not provided by the identity provider.
	// The relay state used if not provided by the identity provider.
	DefaultRelayState *string `json:"defaultRelayState,omitempty" tf:"default_relay_state,omitempty"`

	// (Set of String) The OIDC flows supported by this application.
	// The OIDC flows supported by this application.
	GrantTypes []*string `json:"grantTypes,omitempty" tf:"grant_types,omitempty"`

	// (String) A regex to filter Cloudflare groups returned in ID token and userinfo endpoint.
	// A regex to filter Cloudflare groups returned in ID token and userinfo endpoint.
	GroupFilterRegex *string `json:"groupFilterRegex,omitempty" tf:"group_filter_regex,omitempty"`

	// (String) The unique identifier for the SaaS application.
	// The unique identifier for the SaaS application.
	IdpEntityID *string `json:"idpEntityId,omitempty" tf:"idp_entity_id,omitempty"`

	// (String) The format of the name identifier sent to the SaaS application.
	// The format of the name identifier sent to the SaaS application.
	NameIDFormat *string `json:"nameIdFormat,omitempty" tf:"name_id_format,omitempty"`

	// (String) A JSONata expression that transforms an application's user identities into a NameID value for its SAML assertion. This expression should evaluate to a singular string. The output of this expression can override the name_id_format setting.
	// A [JSONata](https://jsonata.org/) expression that transforms an application's user identities into a NameID value for its SAML assertion. This expression should evaluate to a singular string. The output of this expression can override the `name_id_format` setting.
	NameIDTransformJsonata *string `json:"nameIdTransformJsonata,omitempty" tf:"name_id_transform_jsonata,omitempty"`

	// (String) The public certificate that will be used to verify identities.
	// The public certificate that will be used to verify identities.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`

	// (Set of String) The permitted URL's for Cloudflare to return Authorization codes and Access/ID tokens.
	// The permitted URL's for Cloudflare to return Authorization codes and Access/ID tokens.
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`

	// (String) A JSONata expression that transforms an application's user identities into attribute assertions in the SAML response. The expression can transform id, email, name, and groups values. It can also transform fields listed in the saml_attributes or oidc_fields of the identity provider used to authenticate. The output of this expression must be a JSON object.
	// A [JSONata](https://jsonata.org/) expression that transforms an application's user identities into attribute assertions in the SAML response. The expression can transform id, email, name, and groups values. It can also transform fields listed in the saml_attributes or oidc_fields of the identity provider used to authenticate. The output of this expression must be a JSON object.
	SAMLAttributeTransformJsonata *string `json:"samlAttributeTransformJsonata,omitempty" tf:"saml_attribute_transform_jsonata,omitempty"`

	// (Set of String) Define the user information shared with access.
	// Define the user information shared with access.
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// (String) A globally unique name for an identity or service provider.
	// A globally unique name for an identity or service provider.
	SpEntityID *string `json:"spEntityId,omitempty" tf:"sp_entity_id,omitempty"`

	// (String) The endpoint where the SaaS application will send login requests.
	// The endpoint where the SaaS application will send login requests.
	SsoEndpoint *string `json:"ssoEndpoint,omitempty" tf:"sso_endpoint,omitempty"`
}

type SaasAppParameters struct {

	// (String) The URL where this applications tile redirects users.
	// The URL where this applications tile redirects users.
	// +kubebuilder:validation:Optional
	AppLauncherURL *string `json:"appLauncherUrl,omitempty" tf:"app_launcher_url,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String) The service provider's endpoint that is responsible for receiving and parsing a SAML assertion.
	// The service provider's endpoint that is responsible for receiving and parsing a SAML assertion.
	// +kubebuilder:validation:Optional
	ConsumerServiceURL *string `json:"consumerServiceUrl,omitempty" tf:"consumer_service_url,omitempty"`

	// (Block List) Custom attribute mapped from IDPs. (see below for nested schema)
	// Custom attribute mapped from IDPs.
	// +kubebuilder:validation:Optional
	CustomAttribute []CustomAttributeParameters `json:"customAttribute,omitempty" tf:"custom_attribute,omitempty"`

	// (String) The relay state used if not provided by the identity provider.
	// The relay state used if not provided by the identity provider.
	// +kubebuilder:validation:Optional
	DefaultRelayState *string `json:"defaultRelayState,omitempty" tf:"default_relay_state,omitempty"`

	// (Set of String) The OIDC flows supported by this application.
	// The OIDC flows supported by this application.
	// +kubebuilder:validation:Optional
	GrantTypes []*string `json:"grantTypes,omitempty" tf:"grant_types,omitempty"`

	// (String) A regex to filter Cloudflare groups returned in ID token and userinfo endpoint.
	// A regex to filter Cloudflare groups returned in ID token and userinfo endpoint.
	// +kubebuilder:validation:Optional
	GroupFilterRegex *string `json:"groupFilterRegex,omitempty" tf:"group_filter_regex,omitempty"`

	// (String) The format of the name identifier sent to the SaaS application.
	// The format of the name identifier sent to the SaaS application.
	// +kubebuilder:validation:Optional
	NameIDFormat *string `json:"nameIdFormat,omitempty" tf:"name_id_format,omitempty"`

	// (String) A JSONata expression that transforms an application's user identities into a NameID value for its SAML assertion. This expression should evaluate to a singular string. The output of this expression can override the name_id_format setting.
	// A [JSONata](https://jsonata.org/) expression that transforms an application's user identities into a NameID value for its SAML assertion. This expression should evaluate to a singular string. The output of this expression can override the `name_id_format` setting.
	// +kubebuilder:validation:Optional
	NameIDTransformJsonata *string `json:"nameIdTransformJsonata,omitempty" tf:"name_id_transform_jsonata,omitempty"`

	// (Set of String) The permitted URL's for Cloudflare to return Authorization codes and Access/ID tokens.
	// The permitted URL's for Cloudflare to return Authorization codes and Access/ID tokens.
	// +kubebuilder:validation:Optional
	RedirectUris []*string `json:"redirectUris,omitempty" tf:"redirect_uris,omitempty"`

	// (String) A JSONata expression that transforms an application's user identities into attribute assertions in the SAML response. The expression can transform id, email, name, and groups values. It can also transform fields listed in the saml_attributes or oidc_fields of the identity provider used to authenticate. The output of this expression must be a JSON object.
	// A [JSONata](https://jsonata.org/) expression that transforms an application's user identities into attribute assertions in the SAML response. The expression can transform id, email, name, and groups values. It can also transform fields listed in the saml_attributes or oidc_fields of the identity provider used to authenticate. The output of this expression must be a JSON object.
	// +kubebuilder:validation:Optional
	SAMLAttributeTransformJsonata *string `json:"samlAttributeTransformJsonata,omitempty" tf:"saml_attribute_transform_jsonata,omitempty"`

	// (Set of String) Define the user information shared with access.
	// Define the user information shared with access.
	// +kubebuilder:validation:Optional
	Scopes []*string `json:"scopes,omitempty" tf:"scopes,omitempty"`

	// (String) A globally unique name for an identity or service provider.
	// A globally unique name for an identity or service provider.
	// +kubebuilder:validation:Optional
	SpEntityID *string `json:"spEntityId,omitempty" tf:"sp_entity_id,omitempty"`
}

type SourceInitParameters struct {

	// (String) Friendly name of the Access Application.
	// The name of the attribute as provided by the IDP.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SourceObservation struct {

	// (String) Friendly name of the Access Application.
	// The name of the attribute as provided by the IDP.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SourceParameters struct {

	// (String) Friendly name of the Access Application.
	// The name of the attribute as provided by the IDP.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

// ApplicationSpec defines the desired state of Application
type ApplicationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ApplicationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ApplicationInitParameters `json:"initProvider,omitempty"`
}

// ApplicationStatus defines the observed state of Application.
type ApplicationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ApplicationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Application is the Schema for the Applications API. Provides a Cloudflare Access Application resource. Access Applications are used to restrict access to a whole application using an authorisation gateway managed by Cloudflare.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type Application struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ApplicationSpec   `json:"spec"`
	Status            ApplicationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ApplicationList contains a list of Applications
type ApplicationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Application `json:"items"`
}

// Repository type metadata.
var (
	Application_Kind             = "Application"
	Application_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Application_Kind}.String()
	Application_KindAPIVersion   = Application_Kind + "." + CRDGroupVersion.String()
	Application_GroupVersionKind = CRDGroupVersion.WithKind(Application_Kind)
)

func init() {
	SchemeBuilder.Register(&Application{}, &ApplicationList{})
}
