apiVersion: custom.upbound.io/v1alpha1
kind: SSL
metadata:
  annotations:
    meta.upbound.io/example-id: custom/v1alpha1/ssl
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    customSslOptions:
    - bundleMethod: ubiquitous
      certificate: '-----INSERT CERTIFICATE-----'
      geoRestrictions: us
      privateKeySecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      type: legacy_custom
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
