// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ApplicationInitParameters struct {

	// (Boolean) Enables Argo Smart Routing.
	// Enables Argo Smart Routing.
	ArgoSmartRouting *bool `json:"argoSmartRouting,omitempty" tf:"argo_smart_routing,omitempty"`

	// (Block List, Min: 1, Max: 1) The name and type of DNS record for the Spectrum application. (see below for nested schema)
	// The name and type of DNS record for the Spectrum application.
	DNS []DNSInitParameters `json:"dns,omitempty" tf:"dns,omitempty"`

	// (Block List, Max: 1) The anycast edge IP configuration for the hostname of this application. (see below for nested schema)
	// The anycast edge IP configuration for the hostname of this application.
	EdgeIps []EdgeIpsInitParameters `json:"edgeIps,omitempty" tf:"edge_ips,omitempty"`

	// (Boolean) Enables the IP Firewall for this application.
	// Enables the IP Firewall for this application.
	IPFirewall *bool `json:"ipFirewall,omitempty" tf:"ip_firewall,omitempty"`

	// (Block List, Max: 1) A destination DNS addresses to the origin. (see below for nested schema)
	// A destination DNS addresses to the origin.
	OriginDNS []OriginDNSInitParameters `json:"originDns,omitempty" tf:"origin_dns,omitempty"`

	// (List of String) A list of destination addresses to the origin. e.g. tcp://192.0.2.1:22.
	// A list of destination addresses to the origin. e.g. `tcp://192.0.2.1:22`.
	OriginDirect []*string `json:"originDirect,omitempty" tf:"origin_direct,omitempty"`

	// (Number) Origin port to proxy traffice to. Conflicts with origin_port_range.
	// Origin port to proxy traffice to. Conflicts with `origin_port_range`.
	OriginPort *float64 `json:"originPort,omitempty" tf:"origin_port,omitempty"`

	// 23. Conflicts with origin_port. (see below for nested schema)
	// Origin port range to proxy traffice to. When using a range, the protocol field must also specify a range, e.g. `tcp/22-23`. Conflicts with `origin_port`.
	OriginPortRange []OriginPortRangeInitParameters `json:"originPortRange,omitempty" tf:"origin_port_range,omitempty"`

	// (String) The port configuration at Cloudflare's edge. e.g. tcp/22.
	// The port configuration at Cloudflare's edge. e.g. `tcp/22`.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) Enables a proxy protocol to the origin. Available values: off, v1, v2, simple.
	// Enables a proxy protocol to the origin. Available values: `off`, `v1`, `v2`, `simple`.
	ProxyProtocol *string `json:"proxyProtocol,omitempty" tf:"proxy_protocol,omitempty"`

	// (String) TLS configuration option for Cloudflare to connect to your origin. Available values: off, flexible, full, strict.
	// TLS configuration option for Cloudflare to connect to your origin. Available values: `off`, `flexible`, `full`, `strict`.
	TLS *string `json:"tls,omitempty" tf:"tls,omitempty"`

	// (String) Sets application type. Available values: direct, http, https.
	// Sets application type. Available values: `direct`, `http`, `https`.
	TrafficType *string `json:"trafficType,omitempty" tf:"traffic_type,omitempty"`
}

type ApplicationObservation struct {

	// (Boolean) Enables Argo Smart Routing.
	// Enables Argo Smart Routing.
	ArgoSmartRouting *bool `json:"argoSmartRouting,omitempty" tf:"argo_smart_routing,omitempty"`

	// (Block List, Min: 1, Max: 1) The name and type of DNS record for the Spectrum application. (see below for nested schema)
	// The name and type of DNS record for the Spectrum application.
	DNS []DNSObservation `json:"dns,omitempty" tf:"dns,omitempty"`

	// (Block List, Max: 1) The anycast edge IP configuration for the hostname of this application. (see below for nested schema)
	// The anycast edge IP configuration for the hostname of this application.
	EdgeIps []EdgeIpsObservation `json:"edgeIps,omitempty" tf:"edge_ips,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Enables the IP Firewall for this application.
	// Enables the IP Firewall for this application.
	IPFirewall *bool `json:"ipFirewall,omitempty" tf:"ip_firewall,omitempty"`

	// (Block List, Max: 1) A destination DNS addresses to the origin. (see below for nested schema)
	// A destination DNS addresses to the origin.
	OriginDNS []OriginDNSObservation `json:"originDns,omitempty" tf:"origin_dns,omitempty"`

	// (List of String) A list of destination addresses to the origin. e.g. tcp://192.0.2.1:22.
	// A list of destination addresses to the origin. e.g. `tcp://192.0.2.1:22`.
	OriginDirect []*string `json:"originDirect,omitempty" tf:"origin_direct,omitempty"`

	// (Number) Origin port to proxy traffice to. Conflicts with origin_port_range.
	// Origin port to proxy traffice to. Conflicts with `origin_port_range`.
	OriginPort *float64 `json:"originPort,omitempty" tf:"origin_port,omitempty"`

	// 23. Conflicts with origin_port. (see below for nested schema)
	// Origin port range to proxy traffice to. When using a range, the protocol field must also specify a range, e.g. `tcp/22-23`. Conflicts with `origin_port`.
	OriginPortRange []OriginPortRangeObservation `json:"originPortRange,omitempty" tf:"origin_port_range,omitempty"`

	// (String) The port configuration at Cloudflare's edge. e.g. tcp/22.
	// The port configuration at Cloudflare's edge. e.g. `tcp/22`.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) Enables a proxy protocol to the origin. Available values: off, v1, v2, simple.
	// Enables a proxy protocol to the origin. Available values: `off`, `v1`, `v2`, `simple`.
	ProxyProtocol *string `json:"proxyProtocol,omitempty" tf:"proxy_protocol,omitempty"`

	// (String) TLS configuration option for Cloudflare to connect to your origin. Available values: off, flexible, full, strict.
	// TLS configuration option for Cloudflare to connect to your origin. Available values: `off`, `flexible`, `full`, `strict`.
	TLS *string `json:"tls,omitempty" tf:"tls,omitempty"`

	// (String) Sets application type. Available values: direct, http, https.
	// Sets application type. Available values: `direct`, `http`, `https`.
	TrafficType *string `json:"trafficType,omitempty" tf:"traffic_type,omitempty"`

	// (String) The zone identifier to target for the resource.
	// The zone identifier to target for the resource.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ApplicationParameters struct {

	// (Boolean) Enables Argo Smart Routing.
	// Enables Argo Smart Routing.
	// +kubebuilder:validation:Optional
	ArgoSmartRouting *bool `json:"argoSmartRouting,omitempty" tf:"argo_smart_routing,omitempty"`

	// (Block List, Min: 1, Max: 1) The name and type of DNS record for the Spectrum application. (see below for nested schema)
	// The name and type of DNS record for the Spectrum application.
	// +kubebuilder:validation:Optional
	DNS []DNSParameters `json:"dns,omitempty" tf:"dns,omitempty"`

	// (Block List, Max: 1) The anycast edge IP configuration for the hostname of this application. (see below for nested schema)
	// The anycast edge IP configuration for the hostname of this application.
	// +kubebuilder:validation:Optional
	EdgeIps []EdgeIpsParameters `json:"edgeIps,omitempty" tf:"edge_ips,omitempty"`

	// (Boolean) Enables the IP Firewall for this application.
	// Enables the IP Firewall for this application.
	// +kubebuilder:validation:Optional
	IPFirewall *bool `json:"ipFirewall,omitempty" tf:"ip_firewall,omitempty"`

	// (Block List, Max: 1) A destination DNS addresses to the origin. (see below for nested schema)
	// A destination DNS addresses to the origin.
	// +kubebuilder:validation:Optional
	OriginDNS []OriginDNSParameters `json:"originDns,omitempty" tf:"origin_dns,omitempty"`

	// (List of String) A list of destination addresses to the origin. e.g. tcp://192.0.2.1:22.
	// A list of destination addresses to the origin. e.g. `tcp://192.0.2.1:22`.
	// +kubebuilder:validation:Optional
	OriginDirect []*string `json:"originDirect,omitempty" tf:"origin_direct,omitempty"`

	// (Number) Origin port to proxy traffice to. Conflicts with origin_port_range.
	// Origin port to proxy traffice to. Conflicts with `origin_port_range`.
	// +kubebuilder:validation:Optional
	OriginPort *float64 `json:"originPort,omitempty" tf:"origin_port,omitempty"`

	// 23. Conflicts with origin_port. (see below for nested schema)
	// Origin port range to proxy traffice to. When using a range, the protocol field must also specify a range, e.g. `tcp/22-23`. Conflicts with `origin_port`.
	// +kubebuilder:validation:Optional
	OriginPortRange []OriginPortRangeParameters `json:"originPortRange,omitempty" tf:"origin_port_range,omitempty"`

	// (String) The port configuration at Cloudflare's edge. e.g. tcp/22.
	// The port configuration at Cloudflare's edge. e.g. `tcp/22`.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// (String) Enables a proxy protocol to the origin. Available values: off, v1, v2, simple.
	// Enables a proxy protocol to the origin. Available values: `off`, `v1`, `v2`, `simple`.
	// +kubebuilder:validation:Optional
	ProxyProtocol *string `json:"proxyProtocol,omitempty" tf:"proxy_protocol,omitempty"`

	// (String) TLS configuration option for Cloudflare to connect to your origin. Available values: off, flexible, full, strict.
	// TLS configuration option for Cloudflare to connect to your origin. Available values: `off`, `flexible`, `full`, `strict`.
	// +kubebuilder:validation:Optional
	TLS *string `json:"tls,omitempty" tf:"tls,omitempty"`

	// (String) Sets application type. Available values: direct, http, https.
	// Sets application type. Available values: `direct`, `http`, `https`.
	// +kubebuilder:validation:Optional
	TrafficType *string `json:"trafficType,omitempty" tf:"traffic_type,omitempty"`

	// (String) The zone identifier to target for the resource.
	// The zone identifier to target for the resource.
	// +crossplane:generate:reference:type=github.com/milkpirate/provider-cloudflare/apis/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type DNSInitParameters struct {

	// (String) The name of the DNS record associated with the application.
	// The name of the DNS record associated with the application.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The type of DNS record associated with the application.
	// The type of DNS record associated with the application.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DNSObservation struct {

	// (String) The name of the DNS record associated with the application.
	// The name of the DNS record associated with the application.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The type of DNS record associated with the application.
	// The type of DNS record associated with the application.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DNSParameters struct {

	// (String) The name of the DNS record associated with the application.
	// The name of the DNS record associated with the application.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// (String) The type of DNS record associated with the application.
	// The type of DNS record associated with the application.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type EdgeIpsInitParameters struct {

	// (String) The IP versions supported for inbound connections on Spectrum anycast IPs. Required when type is not static. Available values: all, ipv4, ipv6.
	// The IP versions supported for inbound connections on Spectrum anycast IPs. Required when `type` is not `static`. Available values: `all`, `ipv4`, `ipv6`.
	Connectivity *string `json:"connectivity,omitempty" tf:"connectivity,omitempty"`

	// (Set of String) The collection of customer owned IPs to broadcast via anycast for this hostname and application. Requires Bring Your Own IP provisioned.
	// The collection of customer owned IPs to broadcast via anycast for this hostname and application. Requires [Bring Your Own IP](https://developers.cloudflare.com/spectrum/getting-started/byoip/) provisioned.
	Ips []*string `json:"ips,omitempty" tf:"ips,omitempty"`

	// (String) The type of DNS record associated with the application.
	// The type of edge IP configuration specified. Available values: `dynamic`, `static`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type EdgeIpsObservation struct {

	// (String) The IP versions supported for inbound connections on Spectrum anycast IPs. Required when type is not static. Available values: all, ipv4, ipv6.
	// The IP versions supported for inbound connections on Spectrum anycast IPs. Required when `type` is not `static`. Available values: `all`, `ipv4`, `ipv6`.
	Connectivity *string `json:"connectivity,omitempty" tf:"connectivity,omitempty"`

	// (Set of String) The collection of customer owned IPs to broadcast via anycast for this hostname and application. Requires Bring Your Own IP provisioned.
	// The collection of customer owned IPs to broadcast via anycast for this hostname and application. Requires [Bring Your Own IP](https://developers.cloudflare.com/spectrum/getting-started/byoip/) provisioned.
	Ips []*string `json:"ips,omitempty" tf:"ips,omitempty"`

	// (String) The type of DNS record associated with the application.
	// The type of edge IP configuration specified. Available values: `dynamic`, `static`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type EdgeIpsParameters struct {

	// (String) The IP versions supported for inbound connections on Spectrum anycast IPs. Required when type is not static. Available values: all, ipv4, ipv6.
	// The IP versions supported for inbound connections on Spectrum anycast IPs. Required when `type` is not `static`. Available values: `all`, `ipv4`, `ipv6`.
	// +kubebuilder:validation:Optional
	Connectivity *string `json:"connectivity,omitempty" tf:"connectivity,omitempty"`

	// (Set of String) The collection of customer owned IPs to broadcast via anycast for this hostname and application. Requires Bring Your Own IP provisioned.
	// The collection of customer owned IPs to broadcast via anycast for this hostname and application. Requires [Bring Your Own IP](https://developers.cloudflare.com/spectrum/getting-started/byoip/) provisioned.
	// +kubebuilder:validation:Optional
	Ips []*string `json:"ips,omitempty" tf:"ips,omitempty"`

	// (String) The type of DNS record associated with the application.
	// The type of edge IP configuration specified. Available values: `dynamic`, `static`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type OriginDNSInitParameters struct {

	// (String) The name of the DNS record associated with the application.
	// Fully qualified domain name of the origin.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OriginDNSObservation struct {

	// (String) The name of the DNS record associated with the application.
	// Fully qualified domain name of the origin.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OriginDNSParameters struct {

	// (String) The name of the DNS record associated with the application.
	// Fully qualified domain name of the origin.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type OriginPortRangeInitParameters struct {

	// (Number) Upper bound of the origin port range.
	// Upper bound of the origin port range.
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Number) Lower bound of the origin port range.
	// Lower bound of the origin port range.
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type OriginPortRangeObservation struct {

	// (Number) Upper bound of the origin port range.
	// Upper bound of the origin port range.
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Number) Lower bound of the origin port range.
	// Lower bound of the origin port range.
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type OriginPortRangeParameters struct {

	// (Number) Upper bound of the origin port range.
	// Upper bound of the origin port range.
	// +kubebuilder:validation:Optional
	End *float64 `json:"end" tf:"end,omitempty"`

	// (Number) Lower bound of the origin port range.
	// Lower bound of the origin port range.
	// +kubebuilder:validation:Optional
	Start *float64 `json:"start" tf:"start,omitempty"`
}

// ApplicationSpec defines the desired state of Application
type ApplicationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ApplicationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ApplicationInitParameters `json:"initProvider,omitempty"`
}

// ApplicationStatus defines the observed state of Application.
type ApplicationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ApplicationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Application is the Schema for the Applications API. Provides a Cloudflare Spectrum Application. You can extend the power of Cloudflare's DDoS, TLS, and IP Firewall to your other TCP-based services.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type Application struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dns) || (has(self.initProvider) && has(self.initProvider.dns))",message="spec.forProvider.dns is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.protocol) || (has(self.initProvider) && has(self.initProvider.protocol))",message="spec.forProvider.protocol is a required parameter"
	Spec   ApplicationSpec   `json:"spec"`
	Status ApplicationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ApplicationList contains a list of Applications
type ApplicationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Application `json:"items"`
}

// Repository type metadata.
var (
	Application_Kind             = "Application"
	Application_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Application_Kind}.String()
	Application_KindAPIVersion   = Application_Kind + "." + CRDGroupVersion.String()
	Application_GroupVersionKind = CRDGroupVersion.WithKind(Application_Kind)
)

func init() {
	SchemeBuilder.Register(&Application{}, &ApplicationList{})
}
